import Head from 'next/head';
import React, { useEffect } from 'react';
import styles from '../styles/Home.module.css';

import Header from './components/Header';
import Footer from './components/Footer';

import Aos from 'aos';
import 'aos/dist/aos.css';

import { motion } from 'framer-motion';

const easing = [.6, -.05, .01, .99];

const fadeInUp = {
  initial: {
    y: 60,
    opacity: 0,
  },
  animate: {
    y: 0,
    opacity: 1,
    transition: {
      duration: .6,
      ease: easing,
    },
  },
};

export default function Home() {
  useEffect(() => {
    Aos.init({
        duration: 2000
      });
    }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/currency-converter.png" />
      </Head>
      <Header />
      <motion.main exit={{opacity: 0}} initial='initial' animate='animate' className={styles.main}>
        <motion.div variants={fadeInUp}>
          <h1 className={styles.title}> Welcome to Next.js!</h1>  <p> This is the home page</p>
          <p className={styles.description} data-aos="fade-up">  This is the home page</p>
        </motion.div>
      </motion.main>
      <Footer />
    </div>
  );
}
